#apiVersion: v1
#kind: Service
#metadata:
  #name: nodejs-app-service
#spec:
  #type: NodePort
  #selector:
    #app: node-app
  #ports:
    #- protocol: TCP
      #port: 80
      #targetPort: 3000
      #nodePort: 30007
# for gitlab-registry
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service-gitlab
spec:
  type: NodePort
  selector:
    app: node-app-gitlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30009
